config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  
  resources :games do
    resources :comments
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :ratings

  
  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>',
    large: '500x500>',
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  def self.search(search)
    where("title LIKE ?", "%#{search}%") 
  end
  
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  has_many :games
  
  has_many :comments
  
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
   game = Game.find(params[:game_id])
   
   @comment = game.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    game = Game.find(params[:game_id])
    
    @comment = game.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment.game, notice: 'Comment was successfully created.') }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]




  # GET /games
  # GET /games.json
  def index
   @games = Game.all.reverse_order
   
   if params[:search]
      @games = Game.search(params[:search]).order("created_at DESC")
    else
      @games = Game.all.order("created_at DESC")
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    game = Game.find(params[:id])
    
    @comments = game.comments.reverse_order
    
    @ratings = game.ratings
    
    @sum_ratings = 0
    
    for rating in @ratings
      @sum_ratings = @sum_ratings + rating.value
    end
    
    @average_rating = (@sum_ratings.to_f / @ratings.length).round(1)
  end

  # GET /games/new
  def new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.create(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :creator, :rating, :image, :url, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      @games = Game.all.reverse_order
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    game = Game.find(params[:game_id])
   
   @rating = game.ratings.build
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    game = Game.find(params[:game_id])
    
    @rating = game.ratings.create(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(@rating.game, notice: 'Rating was successfully created.') }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:value, :game_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.game, @comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, placeholder: "Nice game!" %>
  </div>
  
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= comment.game %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Game:</strong>
  <%= @comment.game %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h5>Game Title</h5>
    <%= form.text_field :title, class: "form-control input-lg" %>
  </div>

  <div class="form-group">
    <h5>Game Description</h5>
    <%= form.text_area :description, class: "form-control input-lg" %>
  </div>
  
  <div class="form-group">
    <h5>Upload image</h5>
    <%= form.file_field :image, id:"file-input", class: "form-control input-lg" %>
  </div>

  <div class="form-group">
    <h5>The creator of the game</h5>
    <%= form.text_field :creator, placeholder: "William", class: "form-control input-lg" %>
  </div>
  
   <div class="form-group">
    <h5>Game URL</h5>
    <%= form.text_field :url, placeholder: "https://www.openprocessing.org/sketch/444223", class: "form-control input-lg" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit Game', class: "btn btn-success btn-lg btn-block" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games <%= link_to 'Add Game', new_game_path, class: "btn btn-primary btn-lg" %></h1>



<center>
<% @games.each do |game| %>
    <div class="jumbotron"style="max-width: 700px">
      <%= image_tag game.image(:large), class: 'img-responsive' %>
      <h3><%= link_to game.title, game %></h3>
      
      <%= link_to 'Play Game', game.url, class: "btn btn-danger btn-md" %>
      
      
      
<% if user_signed_in? %>
<% if current_user.id == 1 %>
<br>
    <%= link_to 'Edit', edit_game_path(game), class: "btn btn-danger btn-sm" %>
 
  <% end %>
<% end %>
</div>
<% end %>
</center>
<br>

app/views/games/new.html.erb
<center><h1>Post a New Game</h1></center>

<div style="max-width: 500px; margin: 0 auto">
    <%= render 'form', game: @game %>
</div>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @game.creator %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @average_rating %>
</p>

<%= image_tag @game.image, class: 'img-responsive' %>

<p>
  <strong>User:</strong>
  <%= @game.user %>
</p>

<%= link_to 'Rate this Game', new_game_rating_path(@game), class: "btn btn-primary btn-sm" %>
<%= link_to 'Post a Comment', new_game_comment_path(@game), class: "btn btn-primary btn-sm" %>
<li><%= link_to 'Back', games_path, class: "btn btn-primary btn-sm" %></li>
  
  <% @comments.each do |comment| %>
    <h4><%= comment.body %> posted by <%= comment.user.email %></h4>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kwittgames</title>
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= yield %>
    <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
    <% if(!user_signed_in?) %>
<header class="header-image">
    <div class="headline">
        <div class="container">
            <h2>KwittGames</h2>
            <h5>© Copyright William Kåre Nygård 2017</h5>
            <h3>A great place to post, play and comment</h3>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success btn-lg' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-success btn-lg' %>
        </div>
    </div>
</header>
   <% else %>
  
   <header class="header-image">
    <div class="headline">
        <div class="container">
            <h2>KwittGames</h2>
              <h5>© Copyright William Kåre Nygård 2017</h5>
            <li><%=link_to'Post game', games_path, class: 'btn btn-success btn-lg'%></li>
        </div>
    </div>
</header>
<% end %>


<center>
<% @games.each do |game| %>
    <div class="jumbotron"style="max-width: 700px">
      <%= image_tag game.image(:large), class: 'img-responsive' %>
      <h3><%= link_to game.title, game %></h3>
      
      <%= link_to 'Play Game', game.url, class: "btn btn-danger btn-md" %>
      
      
      
<% if user_signed_in? %>
<% if current_user.id == 1 %>
<br>
    <%= link_to 'Edit', edit_game_path(game), class: "btn btn-danger btn-sm" %>
 
  <% end %>
<% end %>
</div>
<% end %>
</center>

app/views/ratings/_form.html.erb
<%= form_for([@rating.game, @rating]) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.select :value, [["1 star", 1], ["2 stars", 2], ["3 stars", 3], ["4 stars", 4], ["5 stars", 5]], class: "form-control input-lg" %>
  </div>
  
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Game</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.value %></td>
        <td><%= rating.game %></td>
        <td><%= rating.user %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @rating.value %>
</p>

<p>
  <strong>Game:</strong>
  <%= @rating.game %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/shared/_footer.html.erb
<hr>

© Copyright William Nygård 2017

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'KwittGames', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <%= form_tag(games_path, :method => "get", id: "search-form", class: "navbar-form navbar-left" ) do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Games", class: "form-control" %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
      <% end %>
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if(!user_signed_in?) %>
          <li><%=link_to 'Kwitter', 'http://kwitterwilliam.herokuapp.com/tweets'%></li>
            <li><%=link_to 'Bitcamps Website', 'https://www.bitcamp.no/'%></li>
        <% else %>
     
        <li><%=link_to 'Post Game', new_game_path %></li>
            <li><%=link_to 'Kwitter', 'http://kwitterwilliam.herokuapp.com/tweets'%></li>
              <li><%=link_to 'Bitcamps Website', 'https://www.bitcamp.no/'%></li>
              
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome, <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>